# Configuration for defining supported OCI SDK GitHub Repos.
---
owner: oracle
supportedRepos:
- oci-java-sdk
- oci-python-sdk
- oci-cli
- oci-go-sdk
- oci-ruby-sdk
- oci-typescript-sdk
- oci-dotnet-sdk
- oci-powershell-modules